# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "17cb240cc35aedce49ed32a877805a83"
name = "stockeasy-app"
application_url = "https://stockeasy-app.gadget.app/"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_orders,read_inventory,write_inventory,read_locations,write_locations,write_orders"

[auth]
redirect_urls = [ "https://stockeasy-app.gadget.app/api/connections/auth/shopify/callback" ]

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "https://stockeasy-app.gadget.app/api/webhooks/shopify"

[[webhooks.subscriptions]]
topics = [
  "orders/create",
  "orders/updated",
  "products/create",
  "products/update",
  "inventory_levels/connect",
  "inventory_levels/update"
]
uri = "https://stockeasy-app.gadget.app/api/webhooks/shopify"

[[webhooks.subscriptions]]
topics = [ "app_subscriptions/update" ]
uri = "https://stockeasy-app.gadget.app/api/webhooks/app-subscription"
